<h1> Header added to E-Commerce App
Breanna1997/Modern-Cloud pull request #2
Opened 2024-02-16 19:48 UTC by sara-no-h

added <h1> Header to index.html for E-Commerce App

2024-02-17 17:40 UTC, Breanna1997 commented
Not sure about h1 code.

2024-02-17 17:51 UTC, Breanna1997 reviewed
h1 changes

2024-02-20 03:55 UTC, sara-no-h commented
What do you need me to fix with the h1 code?

2024-02-20 04:01 UTC, sara-no-h commented
I am also not seeing the resolve conversation button as described in the project outline.

2024-02-20 04:03 UTC, sara-no-h commented on index.html
What would you like me to change on the h1?

2024-02-20 04:36 UTC, Breanna1997 requested changes
Add color and remove text

2024-02-21 01:08 UTC, Breanna1997 approved these changes

2024-02-21 01:16 UTC, merged